server:
  port: 8080
spring:
  application:
    name: event_hub
  datasource:
    # druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://18.221.171.57:3306/event_hub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: 18.221.171.57
      port: 6379
      database: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
pic:
  path: /home/ec2-user/event_hub/code/event_hub_resource/pic/